# Basic
titanic

###### 1. 행 수, 열 수 출력
###### 2. 컬럼별 타입·결측치 확인
###### 3. 생존자(survived=1)만 필터링
###### 4. 성별에 따른 생존율 계산
###### 5. age 결측치를 중앙값으로 채우기

# Applied
### 그룹별 분석
###### 6. 등급별 평균 나이·요금·생존율 (agg 사용)
###### 7. 1등급 여성 승객 이름 목록
###### 8. 35세 초과 + 1등급 + 남성 승객 수
###### 9. 탑승항(embark_town)별 생존율 비교

In [4]:
import pandas as pd
import numpy as np
TITANIC_URL = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
titanic = pd.read_csv(TITANIC_URL)

In [34]:
# 1. 행 수, 열 수 (rows, columns) 출력
print(f'titanic 데이터셋은 {titanic.shape[0]}행 {titanic.shape[1]}열으로 구성되어 있다.')

titanic 데이터셋은 891행 12열으로 구성되어 있다.

In [ ]:
# 2. 컬럼별 타입, 결측치 확인
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

info() 함수로 DF의 cloumn 별 정보를 확인할 수 있다.  
Age, Cabin, Embarked 에 결측치가 존재한다.

In [57]:
# 3. 생존자(survived = 1)만 필터링
print(titanic[titanic['Survived'] == 1].shape)
titanic[titanic['Survived'] == 1].head()

(342, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [55]:
# 4. 성별에 따른 생존률 계산
print(titanic[(titanic['Survived'] == 1) & (titanic['Sex'] == 'female')].shape)
titanic[(titanic['Survived'] == 1) & (titanic['Sex'] == 'female')].head()

(233, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [ ]:
# 5. Age 결측치를 중앙값으로 채우기
titanic.isnull().sum() # 어떤 열에서 결측치가 몇개 있는 지 확인
titanic['Age'].fillna(titanic['Age'].median()) #fillna 로 결측치를 다른 값으로 채우기

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [68]:
# 6. 등급별 평균 나이, 요금, 생존율(agg 사용)
titanic.groupby('Pclass')
'''위를 실행하면 
<pandas.api.typing.DataFrameGroupBy object at 0x000002A5CB007C50> 
이런 값이 뜨는데 왜 이러는가?'''

titanic.groupby('Pclass').agg(나이 = ('Age','mean'), 요금 = ('Fare','mean'),생존율 = ('Survived','mean'))

               나이         요금       생존율
Pclass
1       38.233441  84.154687  0.629630
2       29.877630  20.662183  0.472826
3       25.140620  13.675550  0.242363

In [70]:
#7. 1등급 여성 승객 이름 목록
titanic['Name'][titanic['Pclass'] == 1]

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
6                                McCarthy, Mr. Timothy J
11                              Bonnell, Miss. Elizabeth
23                          Sloper, Mr. William Thompson
                             ...
871     Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
872                             Carlsson, Mr. Frans Olof
879        Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
887                         Graham, Miss. Margaret Edith
889                                Behr, Mr. Karl Howell
Name: Name, Length: 216, dtype: str

In [77]:
#8. 35세 초과 + 1등급 + 남성 승객 수
titanic[(titanic['Age'] > 35) & (titanic['Pclass'] == 1) & (titanic['Sex'] == 'male')].shape[0]

66

In [84]:
#9. 탑승항(embark_town)별 생존율 비교
titanic.groupby('Embarked').agg( 생존율 =('Survived', 'mean'))

               생존율
Embarked
C         0.553571
Q         0.389610
S         0.336957

## Chanllenge 쇼핑몰 데이터 전처리

In [4]:
import pandas as pd
import numpy as np
np.random.seed(42)
n = 150
shop = pd.DataFrame({
    'customer': np.random.choice(['김민준','이서현','박지우','최하은','정도윤'], n),
    'category': np.random.choice(['의류','전자기기','식품','생활용품','뷰티'], n),
    'quantity': np.random.randint(1, 6, n),
    'price':    np.random.choice([15000,29000,45000,89000,120000], n),
    'rating':   np.random.choice([1,2,3,4,5], n, p=[0.05,0.10,0.20,0.35,0.30]),
    'returned': np.random.choice([True, False], n, p=[0.1, 0.9])
})
shop.loc[np.random.choice(shop.index, 8, replace=False), 'rating'] = float('nan')
shop.to_csv('shop_orders.csv', index=False)

df_shop = pd.read_csv('shop_orders.csv')
# Q1. 카테고리별 총 매출 내림차순
# Q2. 반품률 가장 높은 카테고리
# Q3. rating 결측치를 category별 평균으로 채우기
# Q4. 고객별 총 주문 금액 TOP 3

In [91]:
# Q1. 카테고리별 총 매출 내림차순

# df_shop.groupby('category')
# df_shop.price * df_shop.quantity
df_shop['sales'] = df_shop.price * df_shop.quantity
df_shop.groupby('category').agg( 매출 = ('sales', 'sum')).sort_values(by='매출', ascending=False).reset_index()

  category       매출
0       의류  8235000
1       식품  7302000
2     생활용품  5935000
3       뷰티  4787000
4     전자기기  3099000

In [92]:
# Q2. 반품률 가장 높은 카테고리
# df_shop.groupby('category').agg(반품률 = ('returned', 'mean')) # 뷰티가 0 나와서 확인해보니 진짜 0임

df_shop_returned = df_shop.groupby('category').agg(반품률 = ('returned', 'mean')).sort_values(by='반품률',ascending=False).reset_index()
print(df_shop_returned)

df_shop_returned.loc[0,'category']

  category       반품률
0     전자기기  0.166667
1       의류  0.068182
2     생활용품  0.058824
3       뷰티  0.000000
4       식품  0.000000

'전자기기'

In [ ]:
#Q3. rating 결측치를 category별 평균으로 채우기
print(df_shop.isnull().sum())

# df_shop.groupby('category').agg(rating =('rating', 'mean')) # 카테고리별 평균 구하기
# df_shop.groupby('category')['rating'].transform('mean') 
# # transform : 원본 데이터프레임의 행 개수와 동일하게 유지하여 반환합니다. 
# 즉, 각 행의 카테고리에 맞는 평균값이 쭉 나열된 시리즈(Series)를 만듭니다.
df_shop_rating_fillna = df_shop['rating'].fillna(df_shop.groupby('category')['rating'].transform('mean'))

print(df_shop_rating_fillna.isnull().sum())

customer    0
category    0
quantity    0
price       0
rating      8
returned    0
sales       0
dtype: int64
0

In [90]:
# Q4. 고객별 총 주문 금액 TOP 3

df_shop.groupby('customer').agg(총주문금액 = ('sales', 'sum')).sort_values(by='총주문금액', ascending=False).reset_index().head(3)

  customer    총주문금액
0      최하은  8398000
1      정도윤  6677000
2      김민준  4965000